version: 0.2 

env: 
  variables: 
    AWS_REGION: "us-east-1" 
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb-455472837.us-east-1.elb.amazonaws.com"
  
phases: 
  install: 
    runtime-versions: 
      docker: 18 
  
  
  pre_build: 
    commands:
      - docker login -u nupatrickxu -p 19970929Xpc.
      - echo logging in to ecr... 
      - > 
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 213511591460.dkr.ecr.$AWS_REGION.amazonaws.com 
      # docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) 213511591460.dkr.ecr.us-east-1.amazonaws.com
        
  
  build: 
    commands: 
    - echo building dev images... 
    - docker-compose up -d --build 
    - echo building prod images... 
    - > 
      docker build -f be/Dockerfile -t 213511591460.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:prod ./be
    - > 
      docker build -f fe/Dockerfile -t 213511591460.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:prod --build-arg NODE_ENV=production --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL ./fe

  post_build: 
    commands: 
    - echo pushing prod images to ecr... 
    - docker push 213511591460.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be:prod 
    - docker push 213511591460.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe:prod      